name: Publish to NPM

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      tag_name: ${{ steps.get_version.outputs.tag_name }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: npm ci
        
      - name: Build library
        run: npm run build:lib
        
      - name: Get version info
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "tag_name=v${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
            echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi
        
      - name: Update version (if manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd projects/uae-pass
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          
      - name: Publish to NPM
        id: npm_publish
        run: |
          cd dist/uae-pass
          npm publish --access public
          echo "npm_success=true" >> $GITHUB_OUTPUT
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create_release:
    needs: publish
    runs-on: ubuntu-latest
    if: needs.publish.outputs.npm_success == 'true' || needs.publish.result == 'success'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Read package.json for release notes
        id: package_info
        run: |
          PACKAGE_VERSION=$(node -p "require('./projects/uae-pass/package.json').version")
          PACKAGE_DESC=$(node -p "require('./projects/uae-pass/package.json').description")
          echo "package_version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          echo "package_desc=$PACKAGE_DESC" >> $GITHUB_OUTPUT
        
      - name: Generate changelog
        id: changelog
        run: |
          if [ -f "CHANGELOG.md" ]; then
            # Extract latest version changes from CHANGELOG.md
            CHANGELOG_CONTENT=$(sed -n "/^## \[.*\]/,/^## \[.*\]/p" CHANGELOG.md | head -n -1 | tail -n +2)
            if [ -z "$CHANGELOG_CONTENT" ]; then
              CHANGELOG_CONTENT="- Updated UAE Pass Angular library to version ${{ needs.publish.outputs.version }}"
            fi
          else
            CHANGELOG_CONTENT="- Updated UAE Pass Angular library to version ${{ needs.publish.outputs.version }}"
          fi
          echo "changelog_content<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.publish.outputs.tag_name }}
          release_name: "🥋 Sensei UAE Pass v${{ needs.publish.outputs.version }}"
          body: |
            ## 🚀 UAE Pass Angular Library v${{ needs.publish.outputs.version }}
            
            **Package:** [sensei-uaepass](https://www.npmjs.com/package/sensei-uaepass)
            
            ### 📦 Installation
            ```bash
            npm install sensei-uaepass@${{ needs.publish.outputs.version }}
            ```
            
            ### 📋 Changes
            ${{ steps.changelog.outputs.changelog_content }}
            
            ### 📚 Documentation
            - [Getting Started](https://docs.sensei-uaepass.com)
            - [API Reference](https://docs.sensei-uaepass.com/api-reference)
            - [Examples](https://github.com/${{ github.repository }}/tree/main/examples)
            
            ### 🔗 Links
            - [NPM Package](https://www.npmjs.com/package/sensei-uaepass)
            - [GitHub Repository](https://github.com/${{ github.repository }})
            - [Issues](https://github.com/${{ github.repository }}/issues)
          draft: false
          prerelease: false
